#program 1a
run-a: zad1a.o
	./zad1a.o

zad1a.o: zad1a.c
	gcc zad1a.c

#program 1b
run-b: zad1b.o
	./zad1b

zad1b.o: zad1b.c
	gcc zad1b.c

#program 1c
run-c: zad1c.o
	./zad1c

zad1c.o: zad1c.c
	gcc zad1c.c

#program 1d
run-d: zad1d.o
	./zad1d

zad1d.o: zad1d.c
	gcc zad1d.c

#program 1e
run-e: zad1e.o
	./zad1e

zad1e.o: zad1e.c
	gcc zad1e.c

#czyszczenie
clean:
	rm -rf zad1a zad1b zad1c zad1d zad1e