compile-a:
	gcc zad3a.c -Wall -std=c99 -pedantic -o zad3a

compile-b:
	gcc zad3b.c -Wall -std=c99 -pedantic -o zad3b
	gcc zad3a.c -Wall -std=c99 -pedantic -o zad3a

compile-c:
	gcc zad3c.c -Wall -std=c99 -pedantic -o zad3c
	gcc exec.c -Wall -std=c99 -pedantic -o exec
	gcc zad3a.c -Wall -std=c99 -pedantic -o zad3a

clean:
	rm -rf zad3a zad3b zad3c exec